vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.g.mapleader = " "
vim.cmd("set cursorline")
vim.cmd("set noswapfile")
vim.cmd("set clipboard+=unnamed")
vim.cmd("set rnu")
vim.cmd("set undolevels=1000")
